### ISSUE TITLE
Payments may not complete with infrequent cron jobs

### ISSUE THREAD

**Issue by Wegerich** [WeProgramIT/cryptowoo-monero-addon#9] opened 2019-11-19 21:45 UTC
BTC payments with CW are fine but XMR payments never confirm. I have a few which detect an incoming payment but they very very rarely make it all the way to be set as processing. 

```
2019-11-19T20:35:21+00:00 DEBUG - generate_cryptowoo_form
'Order #26622: Creating address via filter: cw_create_payment_address_XMR returned 4EofuYUS69aPv3LaBTHEADRRESSAkeEkV'
2019-11-19T20:42:33+00:00 DEBUG - do_cryptowoo_cron_action
array (
  'order-processing' => 
  array (
    'tx-update' => 
    array (
      'api_error_transient' => false,
      'payment_data' => 
      array (
        'XMR' => 
        array (
          26622 => 
          array (
            'status' => 'xmrchain.net success | no transactions for address',
            'force_update' => 'no',
            'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
            'order_id' => '26622',
            'total_received_confirmed' => 0,
            'total_received_unconfirmed' => 0,
            'tx_count' => 0,
          ),
        ),
      ),
    ),
    'order-update' => 
    array (
      'unpaid_addresses' => 1,
      'status' => 0,
      'payment_requests' => 
      array (
        26622 => 
        array (
          'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
          'paid' => false,
          'address_in_use' => false,
          'timeout' => 0,
          'times_out_in' => 6769,
          'percentage_paid' => 0,
          'underpayment_range_begin' => 90.0,
          'min_perc_needed_to_complete' => 95.5,
        ),
      ),
    ),
  ),
  'durations' => 
  array (
    'tx-update-duration' => '12.0141sec',
    'order-update-duration' => '0.0034sec',
    'rate-updates' => '0.7987sec',
    'full-runtime' => '13.6913sec',
  ),
  'rate_limit' => 
  array (
    'limit_hour' => 200,
    'confidence_limit_hour' => 15,
    'limit_sec' => 3,
    'time_to_reset' => 1047,
  ),
)
2019-11-19T20:52:11+00:00 DEBUG - do_cryptowoo_cron_action
array (
  'order-processing' => 
  array (
    'tx-update' => 
    array (
      'api_error_transient' => false,
      'payment_data' => 
      array (
        'XMR' => 
        array (
          26622 => 
          array (
            'status' => 'xmrchain.net success | no transactions for address',
            'force_update' => 'no',
            'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
            'order_id' => '26622',
            'total_received_confirmed' => 0,
            'total_received_unconfirmed' => 0,
            'tx_count' => 0,
          ),
        ),
      ),
    ),
    'order-update' => 
    array (
      'unpaid_addresses' => 1,
      'status' => 0,
      'payment_requests' => 
      array (
        26622 => 
        array (
          'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
          'paid' => false,
          'address_in_use' => false,
          'timeout' => 0,
          'times_out_in' => 6191,
          'percentage_paid' => 0,
          'underpayment_range_begin' => 90.0,
          'min_perc_needed_to_complete' => 95.5,
        ),
      ),
    ),
  ),
  'durations' => 
  array (
    'tx-update-duration' => '23.8451sec',
    'order-update-duration' => '0.0066sec',
    'rate-updates' => '0.3089sec',
    'full-runtime' => '24.1638sec',
  ),
  'rate_limit' => 
  array (
    'limit_hour' => 200,
    'confidence_limit_hour' => 15,
    'limit_sec' => 3,
    'time_to_reset' => 469,
  ),
)
2019-11-19T21:02:12+00:00 DEBUG - do_cryptowoo_cron_action
array (
  'order-processing' => 
  array (
    'tx-update' => 
    array (
      'api_error_transient' => false,
      'payment_data' => 
      array (
        'XMR' => 
        array (
          26622 => 
          array (
            'status' => 'xmrchain.net success | no transactions for address',
            'force_update' => 'no',
            'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
            'order_id' => '26622',
            'total_received_confirmed' => 0,
            'total_received_unconfirmed' => 0,
            'tx_count' => 0,
          ),
        ),
      ),
    ),
    'order-update' => 
    array (
      'unpaid_addresses' => 1,
      'status' => 0,
      'payment_requests' => 
      array (
        26622 => 
        array (
          'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
          'paid' => false,
          'address_in_use' => false,
          'timeout' => 0,
          'times_out_in' => 5590,
          'percentage_paid' => 0,
          'underpayment_range_begin' => 90.0,
          'min_perc_needed_to_complete' => 95.5,
        ),
      ),
    ),
  ),
  'durations' => 
  array (
    'tx-update-duration' => '30.2072sec',
    'order-update-duration' => '0.0087sec',
    'rate-updates' => '0.3025sec',
    'full-runtime' => '30.52sec',
  ),
  'rate_limit' => 
  array (
    'limit_hour' => 200,
    'confidence_limit_hour' => 15,
    'limit_sec' => 3,
    'time_to_reset' => 3468,
  ),
)
2019-11-19T21:11:47+00:00 DEBUG - do_cryptowoo_cron_action
array (
  'order-processing' => 
  array (
    'tx-update' => 
    array (
      'api_error_transient' => false,
      'payment_data' => 
      array (
        'XMR' => 
        array (
          26622 => 
          array (
            'status' => 'xmrchain.net success | no transactions for address',
            'force_update' => 'no',
            'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
            'order_id' => '26622',
            'total_received_confirmed' => 0,
            'total_received_unconfirmed' => 0,
            'tx_count' => 0,
          ),
        ),
      ),
    ),
    'order-update' => 
    array (
      'unpaid_addresses' => 1,
      'status' => 0,
      'payment_requests' => 
      array (
        26622 => 
        array (
          'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
          'paid' => false,
          'address_in_use' => false,
          'timeout' => 0,
          'times_out_in' => 5014,
          'percentage_paid' => 0,
          'underpayment_range_begin' => 90.0,
          'min_perc_needed_to_complete' => 95.5,
        ),
      ),
    ),
  ),
  'durations' => 
  array (
    'tx-update-duration' => '9.3325sec',
    'order-update-duration' => '0.0145sec',
    'rate-updates' => '0.3415sec',
    'full-runtime' => '9.6898sec',
  ),
  'rate_limit' => 
  array (
    'limit_hour' => 200,
    'confidence_limit_hour' => 15,
    'limit_sec' => 3,
    'time_to_reset' => 2893,
  ),
)
2019-11-19T21:22:44+00:00 DEBUG - do_cryptowoo_cron_action
array (
  'order-processing' => 
  array (
    'tx-update' => 
    array (
      'api_error_transient' => false,
      'payment_data' => 
      array (
        'XMR' => 
        array (
          26622 => 
          array (
            'status' => 'xmrchain.net success | no transactions for address',
            'force_update' => 'no',
            'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
            'order_id' => '26622',
            'total_received_confirmed' => 0,
            'total_received_unconfirmed' => 0,
            'tx_count' => 0,
          ),
        ),
      ),
    ),
    'order-update' => 
    array (
      'unpaid_addresses' => 1,
      'status' => 0,
      'payment_requests' => 
      array (
        26622 => 
        array (
          'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
          'paid' => false,
          'address_in_use' => false,
          'timeout' => 0,
          'times_out_in' => 4358,
          'percentage_paid' => 0,
          'underpayment_range_begin' => 90.0,
          'min_perc_needed_to_complete' => 95.5,
        ),
      ),
    ),
  ),
  'durations' => 
  array (
    'tx-update-duration' => '18.3948sec',
    'order-update-duration' => '0.0033sec',
    'rate-updates' => '0.7089sec',
    'full-runtime' => '19.1082sec',
  ),
  'rate_limit' => 
  array (
    'limit_hour' => 200,
    'confidence_limit_hour' => 15,
    'limit_sec' => 3,
    'time_to_reset' => 2236,
  ),
)
2019-11-19T21:32:00+00:00 DEBUG - do_cryptowoo_cron_action
array (
  'order-processing' => 
  array (
    'tx-update' => 
    array (
      'api_error_transient' => false,
      'payment_data' => 
      array (
        'XMR' => 
        array (
          26622 => 
          array (
            'status' => 'xmrchain.net success | no transactions for address',
            'force_update' => 'no',
            'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
            'order_id' => '26622',
            'total_received_confirmed' => 0,
            'total_received_unconfirmed' => 0,
            'tx_count' => 0,
          ),
        ),
      ),
    ),
    'order-update' => 
    array (
      'unpaid_addresses' => 1,
      'status' => 0,
      'payment_requests' => 
      array (
        26622 => 
        array (
          'address' => '4EofuYUS69aPv3LaBTHEADRRESSAkeEkV',
          'paid' => false,
          'address_in_use' => false,
          'timeout' => 0,
          'times_out_in' => 3801,
          'percentage_paid' => 0,
          'underpayment_range_begin' => 90.0,
          'min_perc_needed_to_complete' => 95.5,
        ),
      ),
    ),
  ),
  'durations' => 
  array (
    'tx-update-duration' => '21.7782sec',
    'order-update-duration' => '0.0026sec',
    'rate-updates' => '0.2769sec',
    'full-runtime' => '22.0591sec',
  ),
  'rate_limit' => 
  array (
    'limit_hour' => 200,
    'confidence_limit_hour' => 15,
    'limit_sec' => 3,
    'time_to_reset' => 1680,
  ),
)
2019-11-19T21:41:45+00:00 DEBUG - do_cryptowoo_cron_action
array (
  'order-processing' => 
  array (
    'tx-update' => 'No unpaid addresses found',
    'order-update' => 'Transaction data unchanged - processing skipped',
  ),
  'durations' => 
  array (
    'tx-update-duration' => '0.0033sec',
    'order-update-duration' => '0sec',
    'rate-updates' => '0.2901sec',
    'full-runtime' => '0.7416sec',
  ),
  'rate_limit' => 
  array (
    'limit_hour' => 200,
    'confidence_limit_hour' => 15,
    'limit_sec' => 3,
    'time_to_reset' => 1096,
  ),
)
```

I'm using WooCommerce 3.8, latest version of CW, 1.0.3 for monero addon and latest wordpress. This problem has been happening for quite a long time but it didn't _always_ happen.

My monero GUI client shows the payment time as 20:53:32 and the full amount is paid.

**Comment by Olsm** [comment] 2019-11-22 14:27
Hey @Wegerich I am sorry to hear the issues you are experiencing. Could you please tell me which wallet you are using? Which type of view key are you using, the public view key or private view key? We have been using Moneroju Android Wallet during testing, would you be able to try that? It would help us pinpoint if this issue is related to Monero wallets / addresses / view keys. If it works then please use that while we work on solving this issue. If not then please use the force complete payment feature you find in wp-admin orders overview and manually enter the txid and click complete order.

Also please be aware that an issue in your server may cause the API calls to fail and this may be the cause. But if as you see order processing works for other currencies in your store then this is less likely.

**Comment by Olsm** [comment] 2019-11-22 18:28
@Wegerich Can you please try to update to version v1.0.4 that you can download here and report back if it then works? 
https://github.com/WeProgramIT/cryptowoo-monero-addon/releases/tag/v1.0.4

**Comment by Wegerich** [comment] 2019-11-22 18:52
Thanks Olav, I just updated cryptowoo-monero-addon.php to include the change from version 1.0.4 and I changed the version number too. 

I am using the GUI client from https://www.getmonero.org/downloads/ this is the official client as far as I am aware. I think monero.org might be a fork? I have to go out right now but let's discuss this tomorrow.

**Comment by Wegerich** [comment] 2019-11-23 12:32
Ok, I am just checking all this now.

I have made a test payment and it was detected on the network fine, then it changed to processing OK too. Therefore I am very hopeful that this new change has fixed the problem.

**Comment by Olsm** [comment] 2019-11-23 17:21
Thank you @Wegerich as you said it is working now I am going to close this issue and instruct CryptoWoo to push out the update. Let me know if it occurs again and we will reopen the issue.

**Comment by Wegerich** [comment] 2019-11-26 20:38
Unfortunately I just had a payment from a customer with the same problem. No incoming payment detected at any point. Order timed out.

**Comment by Olsm** [comment] 2019-11-27 22:37
@Wegerich I am sorry to hear you are still having issues. I think it would help me find the issue if you can send me the monero wallet address and view key combination as well as the order details date, amount of xmr, payment address, and in what block the transaction was confirmed. The block height the tx was confirmed at you can find in your monero gui wallet. Alternatively if you do not want to expose it for privacy reasons I would like to ask you to create a new monero address and view key and then reproduce the issue with a failing order and give me that info instead.

Alternatively you may give me access to your website and it could help me to look more into the issue and find the cause of it but that would only be necessary if i could not succeed reproducing the issue in the previous method i mentioned.

Please send this info on email to olav@weprogram.it. I will get back to you some time tomorrow when/if I have received it.

**Comment by Wegerich** [comment] 2019-11-27 22:52
Thanks, I sent you an email with a login for the site.

**Comment by Olsm** [comment] 2019-11-28 00:59
The issue here seems to be that the cron jobs are infrequent and irregular, by that I mean they run with minimum 5 minutes pause between cron jobs, and use WordPress cron jobs instead of external frequent regular cron jobs. I explained the issue in full details in the email to you and suggested the solution being setting up external regular and frequent (minimum once a minute, recommended 4 times a minute) cron jobs and disabling the built in WordPress cron job schedule. I will wait for your response and I hope this will solve the issue.

**Comment by Olsm** [comment] 2020-01-04 19:28
@Wegerich Has this issue been completely solved or has it occured again since the last changes? I think we are ready to release version v1.0.5 fixing this and the other issue.

**Comment by Wegerich** [comment] 2020-01-04 19:29
No payments have been missed since I updated, so I would say this issue could be closed.

**Closed** 2020-01-04 19:55 UTC
Labels: bug, enhancement
